# Getting Start with Tensorflow Operator

## Goal
In this notebook, we're going to getting start with tensorflow Operators. What are tensorflow operators and we will run some of them.




## Introduction to Operator
Tensorflow prodives certain predefined operators that can be performed on tensors. Tensorflow operator helps us to perform basic operation on tensor easily.
___
There are sevral types of operations that can be done on tensorflow. Some of them are mentioned below:
* Arithmetic operations : add, subtract, multiply,...
* Matrix operations : matmul, matrix_inverse, ...
* Control flow operations : tuple, group, ...
* Logical operations : logical_and, logical_not, ...
* Comparision operations: equal, less, not_equal, ...
* Debugging operations : is_finite, is_inf,..

___
[Here](https://www.tensorflow.org/lite/guide/op_select_allowlist) is the list of all the operator in tensorflow. We will perform some of the operator on our tensor A1 and A2.
we will start with 



## Tensor 
We will start by importing installed TensorFlow library into your workspace under the alias tf:

Note:- You can also install TensorFlow with Conda if you’re working on Windows or it’s best to check [the official installation instructions](https://www.tensorflow.org/install).

In [42]:
import tensorflow as tf

## Data for learning
First we define two variables that are actually constants. Pass an array of four numbers to the constant() function so that we can perform  operator method on this.

In [43]:
# Initialize two constants
tensor_A1  = tf.constant([1,6,2,8])
tensor_A2  = tf.constant([9,4,3,0])

### Arithmetic Operations
Tensorflow provide several operation to perform basic arithmetic operators to tensor.

ex - tf.add, tf.subtract, tf.multiply, tf.divide and ...

#### ADD
return addition of two tensor.

In [44]:
tensor_add = tf.add(tensor_A1, tensor_A2)
print(tensor_add)  

tf.Tensor([10 10  5  8], shape=(4,), dtype=int32)


#### Multiply
this operator return element wise multiplication of two tensor.

In [45]:
tensor_multiply = tf.multiply(tensor_A1, tensor_A2)
print(tensor_multiply)  

tf.Tensor([ 9 24  6  0], shape=(4,), dtype=int32)


### Matrix operations
Tensorflow provide several operation to perform matrices operation to tensor.

ex - tf.diag, tf.transpose, tf.matrix_inverse, tf.norm and ...

#### Transpose
this operator return transpose of a tensor.

In [46]:
tensor_transpose = tf.transpose(tensor_A1)
print(tensor_transpose)  

tf.Tensor([1 6 2 8], shape=(4,), dtype=int32)


### Control flow operations
Tensorflow provide several operation that can be used to control the execution of operation and add conditional dependencies.

ex - tf.identity, tf.tuple, tf.group, tf.cond and ...

#### Identity
Return a tensor with the same shape and contents as the input tensor or value.

In [47]:
tensor_identity = tf.identity(tensor_A1)
print(tensor_identity)  

tf.Tensor([1 6 2 8], shape=(4,), dtype=int32)


### Logical operations
Tensorflow provide several operation that can be used to add logical operation on tensor.

ex -  logical_and, logical_not, logical_or logical_xor...

In [48]:
# Initialize two constants
x  = tf.constant([False,False,True,True])
y  = tf.constant([False,True,True,False])

#### LogicalOr
Returns the truth value of x OR y element-wise.

In [49]:
tensor_or = tf.math.logical_or(x,y)
print(tensor_or)  

tf.Tensor([False  True  True  True], shape=(4,), dtype=bool)


### Comparision operations
Tensorflow provide several operation that can be used to add comparison operation on tensor.

ex -  tf.equal, tf.not_equal,tf.less,tf.grater,...

#### Equal
Returns the truth value of (x == y) element-wise.

In [50]:
tensor_equal = tf.equal(tensor_A1,tensor_A2)
print(tensor_equal)  

tf.Tensor([False False False False], shape=(4,), dtype=bool)


### Debugging operations
Tensorflow provide several operation that can be used to validate values.

ex -  tf.is_finite, tf.us_inf,tf.is_nana,...

#### isFinite
Returns which elements of x are finite.

In [51]:
x = tf.constant([5.0, 4.8, 6.8, np.inf, np.nan])
tensor_finite = tf.math.is_finite(x) 
print(tensor_finite)

tf.Tensor([ True  True  True False False], shape=(5,), dtype=bool)


### Conclusion
Tensorflow operation is very useful in especially when we are working with tensor and matrix. [Click Here](https://www.tensorflow.org/lite/guide/op_select_allowlist) to visit list of all the operator in tensorflow.
